spring:
  profiles:
    default: dev
    active: dev
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: jdbc:postgresql://localhost:5432/demo_db
    username: postgres
    password: 123456
  cache:
    type: redis
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  redis:
    host: localhost
    port: 6379

logging:
  level:
    org:
      springframework:
        cache: TRACE
